const mongoose = require("mongoose");
const ObjectId = mongoose.Schema.Types.ObjectId;

const PaymentSchema = new mongoose.Schema(
  {
    // User (the person doing the payment, or for whom the payment is done.)
    user: { type: ObjectId, ref: "User", required: true },
    // Amount (Total, Paid, Due)
    amount: { type: Number, required: true, default: 0 },
    amountPaid: { type: Number, required: true, default: 0 },
    amountDue: { type: Number, required: true, default: 0 },
    // Payment For? Event or?
    paymentFor: {
      type: String,
      default: "default",
      enum: ["default", "event", "makeup-and-beauty"],
      required: true,
    },
    event: { type: ObjectId, ref: "Event", default: null },
    order: { type: ObjectId, ref: "Order", default: null },
    // Payent Method (Cash, UPI, Bank Transfer [Added by Admin], Razorpay)
    paymentMethod: {
      type: String,
      default: "default",
      enum: ["default", "razporpay", "cash", "upi", "bank-transfer"],
      required: true,
    },
    razporPayId: { type: String, default: "" },
    response: { type: [Object], default: [] },
    // ── MB7a (additive) — onboarding & money engine ──────────────────────────
    // Which milestone this payment is for (onboarding fee / advance / balance).
    milestone: { type: String, enum: ["", "onboarding", "advance", "balance"], default: "" },
    // Razorpay payment-link (when generated; dormant-safe).
    paymentLinkId: { type: String, default: "" },
    paymentLinkUrl: { type: String, default: "" },
    // Offline payment proof. Screenshot URL (S3) mandatory for bank-transfer.
    proof: {
      url: { type: String, default: "" },
      txnId: { type: String, default: "" },
      paidOn: { type: Date, default: null },
      notes: { type: String, default: "" },
    },
    recordedBy: { type: ObjectId, ref: "Admin", default: null },
    // Reminder-due marker (the actual WhatsApp chase is template-gated/dormant).
    reminderDueAt: { type: Date, default: null },
    // Auto-invoice (Slice 6): stamped when the payment is recorded so the
    // invoice is "available" (downloadable at GET /payment/:id/invoice), not
    // only generated on demand.
    invoiceReadyAt: { type: Date, default: null },
    // Payment Status: null, created, attempted, paid, partially paid, expired, cancelled
    status: {
      type: String,
      required: true,
      default: "null",
      enum: [
        "null",
        "created",
        "attempted",
        "paid",
        "partially_paid",
        "expired",
        "canceled",
      ],
    },
    transactions: { type: Array, default: [] },
    // ── COUPLE APP (additive, optional) ───────────────────────────────────────
    // The couple app REUSES this model rather than opening a second payments
    // collection: this is already the row Razorpay writes to, the CRM reads and
    // the invoice is cut from, and two payment records per payment is the class
    // of problem § 06.3 of the couple-app spec exists to prevent.
    //
    // What it did not carry is the SCHEDULE half of a couple-facing row — the
    // label they read, the vendor, the date it falls due, and how much of the
    // Wedsy Wallet was applied. Those live here, all optional, none of them
    // read by any existing surface. No field above changes.
    //
    // Rows are generated by services/CoupleDecorFinaliseService (§ 06.3, décor
    // finalise → payment schedule) and keyed by `sourceKey` so generating them
    // twice updates the same rows instead of doubling the schedule.
    coupleApp: {
      // Denormalised from `event` so a couple-app read filters on one indexed
      // field without also having to trust paymentFor.
      weddingId: { type: ObjectId, ref: "Event", default: null },
      label: { type: String, default: "" },      // "Décor instalment 1"
      vendor: { type: String, default: "" },     // "Taj West End" | "Wedsy"
      ref: { type: String, default: "" },        // "WD-2026-0602"
      dueDate: { type: Date, default: null },
      walletApplied: { type: Number, default: 0 },
      // Idempotency key for the generated schedule, e.g. "decor:<dayId>:2".
      sourceKey: { type: String, default: "" },
    },
  },
  { timestamps: true }
);
PaymentSchema.index({ "coupleApp.weddingId": 1, "coupleApp.dueDate": 1 });
// The idempotent schedule upsert (§ 06.3): one row per source key per wedding.
PaymentSchema.index(
  { "coupleApp.weddingId": 1, "coupleApp.sourceKey": 1 },
  { unique: true, sparse: true }
);

module.exports = mongoose.model("Payment", PaymentSchema);
